config/routes.rb
Rails.application.routes.draw do
  root 'posts#welcome_page'

  get 'profiles/:id/follow' => 'profiles#follow', as: :follow
  get 'profiles/:id/unfollow' => 'profiles#unfollow', as: :unfollow

  get 'profiles/users/:username' => 'profiles#user_page', as: :user_page

  resources :profiles
  resources :posts

  devise_for :users, controllers: {
    confirmations:  "users/confirmations",
    # omniauth_callbacks: 'users/omniauth_callbacks'
    passwords:      "users/passwords",
    registrations:  "users/registrations",
    sessions:       "users/sessions",
    unlocks:        "users/unlocks"
  }

  #Wicked Wizard
  resources :after_signup



end

app/models/post.rb
class Post < ActiveRecord::Base
  paginates_per 50
  belongs_to :user
  validates_length_of :body, maximum: 170

  def self.timeline(user)
    following_ids = user.all_following.map(&:id)
    all_ids= following_ids << user.id
    Post.where(user_id: all_ids).order("created_at DESC")
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(created_at: :desc).page params[:page]
  end

  def welcome_page
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    redirect_to posts_path
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id if current_user %>
  </div>
  <div class="actions">
    <%= f.submit 'MEEP', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="row">
  <div class="post">
    <div class="avitar col-lg-1 col-md-2 col-xs-4 pic-preview">
      <%= link_to user_page_path(username: post.user.username) do %>
        <div class="thumbnail">
          <img src="<%=post.user.image%>" alt="Missing Image"/>
        </div>
      <% end %>
    </div>
    <div class="col-lg-10 col-md-9 col-sm-8 col-xs-5">
        <p class="post-body">
          <%= post.body %>
        </p>
      <p><em>submitted <%= time_ago_in_words(post.created_at) %> ago by @<%= post.user.username %></em></p>
      <% if (post.user != current_user) %>
        <% if !current_user.following?(post.user) %>
          <p><em><%= link_to "follow #{post.user.username}", follow_path( id: post.user.id ) %></em></p>
        <% elsif current_user.following?(post.user) %>
          <p><em><%= link_to "unfollow #{post.user.username}", unfollow_path( id: post.user.id ) %></em></p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'MEEP!', new_post_path, class: "btn btn-primary" %>
<% end %>
<div class="row">
  <div class="col-xs-12" style="height:20px;"></div>
</div>
<%= render partial: 'post', collection: @posts %>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Meep</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/welcome_page.html.erb
<div class="row">
  <div class="welcome col-xs-10 col-xs-offset-2">
    <h1>Meeper</h1>
      <% if !user_signed_in? %>
      <ul>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      </ul>
      <% else %>
      <ul>
        <li><%= link_to "Your profile", user_page_path(:username => current_user.username) %></li>
      </ul>
      <% end %>
  </div>
  </div>